---
image:
    name: dimtass/stm32-cde-image:0.1
    entrypoint: [""]

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build

build:
    stage: build
    script: time TOOLCHAIN_DIR=/opt/toolchains/gcc-arm-none-eabi-9-2019-q4-major ./build.sh
    cache:
        key: build-cache
        paths:
        - build-stm32/src
    artifacts:
        paths:
        - build-stm32/src/stm32f303-app.bin
        expire_in: 1 week